input:
    data_path: C:\Users\DChen\Projects\RFA\Data\input
    fn: UPDATED_2022 recovery plans Revised Template_1_23_23.xlsx
    var:
      Jurisdication:
        sheet: 'Funding and ratings'
        colpos: A:C
        skiprow: 2
        skipfooter: 0
        colnames:
          - Level_of_Goverment
          - State
          - Jurisdication
      PlanInvest:
        sheet: 'Plan Investment'
        colpos: A:O
        skiprow: 1
        skipfooter: 0
        colnames:
          - Level_of_Goverment
          - State
          - Jurisdication
          - PIA1
          - PIA2
          - PIA3
          - PIA4
          - PIA5
          - PIA6
          - PIA7
          - PIA8
          - PIA9
          - PIA10
          - PIA11
          - PIA12
      Fund:
        sheet: 'Funding and ratings'
        colpos: A:I,S:AN
        skiprow: 5
        skipfooter: 0
        colnames:
          - Level_of_Goverment
          - State
          - Jurisdication
          - SLFRF_Award
          - Population
          - Award_Per_Capita
          - RecoveryPlan_2021
          - RecoveryPlan_Interim
          - RecoveryPlan_2022
          - Num_Projects
          - EvidenceBasedIntervention_2022
          - proofEvidenceBased_2022
          - EvidenceBasedScore_2022
          - InvestEvaluation_2022
          - InvestEvaluationPilot_2022
          - ImpactEvaluationScore_2022
          - UseDataEvidence_2022
          - EnhanceDataEvidence_2022
          - EnhanceDataEvidenceScore_2022
          - OutreachUnderserved_2022
          - OutreachCommunityStakeholder_2022
          - MultipleOutreachMethod_2022
          - EnageCommunity_2022
          - CommunityFeedback_2022
          - CommunityEngagementScore_2022
          - IdentifyUnderServe_2022
          - EquityMethod_2022
          - FollowEquityMethod_2022
          - EquityInform_2022
          - EquityImpact_2022
          - EquityOutcomeScore_2022
        urllink:
          - G
          - H
          - I
      InvestmentArea:
        sheet: 'Investment areas & coding'
        colpos: A:H, I:P, Q,S:AF, AO
        skiprow: 4
        skipfooter: 0
        colnames:
          - Level_of_Goverment
          - State
          - Jurisdication
          - Agency
          - InvestmentAreaLevel1
          - InvestmentAreaLevel2
          - Activity
          - Project_ID
          - Pilot
          - Scaling
          - ActivityFund
          - TotalARPFund
          - EvidenceBased
          - EvidenceBasedKeyword
          - EvidenceBasedSrc
          - EvidenceBasedAmount
          - EvidenceLevel
          - Review
          - StrategyName
          - EvidenceBasedConfirm
          - InvestmentEvaluation
          - ImpactEvaluation
          - ImpactEvaluationSrc
          - ImpactEvaluationAmount
          - ConfirmEvaluation
          - DataEvidence
          - DataEvidenceSrc
          - SupportSTAFF
          - SupportIT
          - ConfirmDataEvidence
          - DataEvidenceAmount
          - ManualProjectSummary
      RFAInvestmentAreaMeta:
        sheet: RFA investment areas
        colpos: A:G
        skiprow: 1
        skipfooter: 0
        colnames:
          - InvestmentArea
          - Keywords
          - Origin
          - RFAPriority
          - Stakeholder
          - IssueArea
          - ECCategory
    data21:
      data_path: C:\Users\DChen\Projects\RFA\Data\input
      fn: cleandat.xlsx
      Ranking: 
        sheet: wide
        colpos: B,C,F, BA:BF
        skiprow: 1
        skipfooter: 0
        colnames:
          - Jurisdication
          - Level_of_Goverment
          - State
          - EnhanceDataEvidenceScore_2021
          - EvidenceBasedScore_2021
          - ImpactEvaluationScore_2021
          - CommunityEngagementScore_2021
          - EquityOutcomeScore_2021
          - Score_2021
    TreasuryData:
      files:
        EC22:
          path: C:\Users\DChen\Projects\RFA\Data\input
          fn: July-2022-Quarterly-Reporting-Data-through-June-30-2022.xlsx
          var:
            Recipients:
              sheet: Recipients
              colpos: A:E,G:H
              skiprow: 1
              skipfooter: 0 
              colnames:
                - Recipient_ID
                - RecipientName
                - State
                - ReportingTier
                - RecipientType
                - SLFRF_Award
                - Num_Projects
            Projects:
              sheet: Projects
              colpos: A:N
              skiprow: 1
              skipfooter: 0 
              colnames:
                - Project_ID
                - Recipient_ID
                - RecipientName
                - State
                - ReportingTier
                - RecipientType
                - CompletionStatus
                - ProjectName
                - ExpenditureCategoryGroup
                - ExpenditureCategory
                - ProjectDescription
                - AdoptedBudget
                - Cumulative_Obligations
                - Cumulative_Expenditures
            Plan:
              sheet: Recovery Plans
              colpos: A,H
              skiprow: 1
              skipfooter: 0 
              colnames:
                - Recipient_ID
                - URL
        EC22mapping:
          path: C:\Users\DChen\Projects\RFA\Data\input
          fn: Copy of updated_recipient_id_july_2022_mathematica_jurisdictions.xlsx
    sr:
      - EvidenceBased2022
      - ImpactEvaluation2022
      - DataEvidence2022
      - EngageCommunity2022
      - EquitableOutcome2022
      - EvidenceBased2021
      - ImpactEvaluation2021
      - DataEvidence2021
      - EngageCommunity2021
      - EquitableOutcome2021
    investArea:
      PIA1: COVID Mitigation and Prevention
      PIA2: Public Health
      PIA3: Behavioral health
      PIA4: Intergovernmental Collaboration
      PIA5: Housing & Homelessness Services
      PIA6: Parks and Recreation
      PIA7: Early Childhood
      PIA8: K-12 Education
      PIA9: Financial Security
      PIA10: Workforce Development
      PIA11: Justice and Public Safety
      PIA12: Infrastructure
    investAreaMapping:
      COVID Mitigation and Prevention:
        - COVID Mitigation and Prevention
      Public Health:
        - Public health
      Behavioral health:
        - Mental health 
        - Substance use 
        - Behavioral health
      Intergovernmental Collaboration:
        - State/local government collaboration
        - City/county collaboration
      Housing & Homelessness Services:
        - Building affordable housing
        - Building housing for people experiencing homelessness 
        - Home/rental assistance 
        - Services for people experiencing homelessness
      Parks and Recreation:
        - Community development
      Early Childhood:
        - Childcare
        - Early childhood programs
        - Pre-K programs
        - Infant/childcare and maternal health 
      K-12 Education:
        - High dosage tutoring programs
        - Summer/extended learning programs
        - School facility improvements
        - City/county - school district collaboration
        - Educational tech/broadband access
        - Education
      Financial Security:
        - Financial stability
        - Guaranteed income/cash transfers
      Workforce Development:
        - Career prep programs
        - Workforce development & training 
      Justice and Public Safety:
        - Public safety
        - Justice
      Infrastructure:
        - Broadband
    InvestmentAreaDef: C:\Users\DChen\Projects\RFA\Data\input\InvestmentAreaDefinition.xlsx
output:
  path: C:\Users\DChen\Projects\RFA\Data\output














