input:
    data_path: N:\Project\51448_ARPA\DC1\6. Data\mockup
    fn: UPDATED_2022 recovery plans Revised Template.xlsx
    # data_path: N:\Project\51448_ARPA\DC1\6. Data\
    # fn: 2022 recovery plans_draft template_v2_mockup.xlsx
    var:
      Jurisdication:
        sheet: 'Funding and ratings'
        colpos: A:C
        skiprow: 2
        skipfooter: 0
        colnames:
          - Level_of_Goverment
          - State
          - Jurisdication
      PlanInvest:
        sheet: 'Plan Investment'
        colpos: B:P
        skiprow: 1
        skipfooter: 0
        colnames:
          - Level_of_Goverment
          - State
          - Jurisdication
          - PIA1
          - PIA2
          - PIA3
          - PIA4
          - PIA5
          - PIA6
          - PIA7
          - PIA8
          - PIA9
          - PIA10
          - PIA11
          - PIA12
      Fund:
        sheet: 'Funding and ratings'
        colpos: A:I,S:AN
        skiprow: 5
        skipfooter: 2
        colnames:
          - Level_of_Goverment
          - State
          - Jurisdication
          - SLFRF_Award
          - Population
          - Award_Per_Capita
          - RecoveryPlan_2021
          - RecoveryPlan_Interim
          - RecoveryPlan_2022
          - Num_Projects
          - EvidenceBasedIntervention_2022
          - proofEvidenceBased_2022
          - EvidenceBasedScore_2022
          - InvestEvaluation_2022
          - InvestEvaluationPilot_2022
          - ImpactEvaluationScore_2022
          - UseDataEvidence_2022
          - EnhanceDataEvidence_2022
          - EnhanceDataEvidenceScore_2022
          - OutreachUnderserved_2022
          - OutreachCommunityStakeholder_2022
          - MultipleOutreachMethod_2022
          - EnageCommunity_2022
          - CommunityFeedback_2022
          - CommunityEngagementScore_2022
          - IdentifyUnderServe_2022
          - EquityMethod_2022
          - FollowEquityMethod_2022
          - EquityInform_2022
          - EquityImpact_2022
          - EquityOutcomeScore_2022
        urllink:
          - G
          - H
          - I
      Fund1:
        sheet: 'Funding and ratings old'
        colpos: A:C,D:F,J,S, AI:AR
        skiprow: 2
        skipfooter: 0
        colnames:
          - Level_of_Goverment
          - State
          - Jurisdication
          - SLFRF_Award
          - Population
          - Award_Per_Capita
          - Obligated_Funds
          - Expended_Funds
          - EvidenceBased2022
          - ImpactEvaluation2022
          - DataEvidence2022
          - EngageCommunity2022
          - EquitableOutcome2022
          - EvidenceBased2021
          - ImpactEvaluation2021
          - DataEvidence2021
          - EngageCommunity2021
          - EquitableOutcome2021
      InvestmentArea:
        sheet: 'Investment areas & coding'
        colpos: A:O, R:W, Z
        skiprow: 4
        skipfooter: 0
        colnames:
          - Level_of_Goverment
          - State
          - Jurisdication
          - Agency
          - InvestmentAreaLevel1
          - InvestmentAreaLevel2
          - Activity
          - Pilot
          - Scaling
          - ActivityFund
          - TotalARPFund
          - EvidenceBased
          - EvidenceBasedKeyword
          - EvidenceBasedSrc
          - EvidenceBasedAmount
          - InvestmentEvaluation
          - ImpactEvaluation
          - ImpactEvaluationSrc
          - ImpactEvaluationAmount
          - DataEvidence
          - DataEvidenceSrc
          - DataEvidenceAmount
      EC:
        sheet: 'Expended funds by ECs 2021-22'
        colpos: A:G, H, J, L,  O, Q, S,V, X, Z,  AC, AE, AG,  AJ, AL, AN,AQ,AS,AU, AX,AZ,BB
        skiprow: 5
        skipfooter: 1
        colnames:
          - Level_of_Goverment
          - State
          - Jurisdication
          - Expenditure
          - ExpenditureSinceLastReport
          - Expenditure_Interim
          - Expenditure_2011
          - EC1_2022
          - EC1_Interim
          - EC1_2021
          - EC2_2022
          - EC2_Interim
          - EC2_2021
          - EC3_2022
          - EC3_Interim
          - EC3_2021
          - EC4_2022
          - EC4_Interim
          - EC4_2021
          - EC5_2022
          - EC5_Interim
          - EC5_2021
          - EC6_2022
          - EC6_Interim
          - EC6_2021
          - EC7_2022
          - EC7_Interim
          - EC7_2021
      RFAInvestmentAreaMeta:
        sheet: RFA investment areas
        colpos: A:G
        skiprow: 1
        skipfooter: 0
        colnames:
          - InvestmentArea
          - Keywords
          - Origin
          - RFAPriority
          - Stakeholder
          - IssueArea
          - ECCategory
    sr:
      - EvidenceBased2022
      - ImpactEvaluation2022
      - DataEvidence2022
      - EngageCommunity2022
      - EquitableOutcome2022
      - EvidenceBased2021
      - ImpactEvaluation2021
      - DataEvidence2021
      - EngageCommunity2021
      - EquitableOutcome2021
    investArea:
      PIA1: COVID Mitigation and Prevention
      PIA2: Public Health
      PIA3: Behavioral health
      PIA4: Intergovernmental Collaboration
      PIA5: Housing & Homelessness Services
      PIA6: Parks and Recreation
      PIA7: Early Childhood
      PIA8: K-12 Education
      PIA9: Financial Security
      PIA10: Workforce Development
      PIA11: Justice and Public Safety
      PIA12: Infrastructure
       
output:
  path: N:\Project\51448_ARPA\DC1\6. Data\mockup\output

data21:
  data_path: C:\Users\DChen\Projects\RFA\output\B3
  fn: cleandat.xlsx
  Ranking: 
    sheet: wide
    colpos: B,C,F, BA:BF
    skiprow: 1
    skipfooter: 0
    colnames:
      - Jurisdication
      - Level_of_Goverment
      - State
      - EnhanceDataEvidenceScore_2021
      - EvidenceBasedScore_2021
      - ImpactEvaluationScore_2021
      - CommunityEngagementScore_2021
      - EquityOutcomeScore_2021
      - Score_2021

TreasuryData:
  files:
    EC22:
      path: N:\Project\51448_ARPA\DC1\6. Data\ExpenditureFromTreasury
      fn: July-2022-Quarterly-Reporting-Data-through-June-30-2022.xlsx
      var:
        Recipients:
          sheet: Recipients
          colpos: A:E,G:H
          skiprow: 1
          skipfooter: 0 
          colnames:
            - Recipient_ID
            - RecipientName
            - State
            - ReportingTier
            - RecipientType
            - SLFRF_Award
            - Num_Projects
        Projects:
          sheet: Projects
          colpos: A:N
          skiprow: 1
          skipfooter: 0 
          colnames:
            - Project_ID
            - Recipient_ID
            - RecipientName
            - State
            - ReportingTier
            - RecipientType
            - CompletionStatus
            - ProjectName
            - ExpenditureCategoryGroup
            - ExpenditureCategory
            - ProjectDescription
            - AdoptedBudget
            - Cumulative_Obligations
            - Cumulative_Expenditures
        Plan:
          sheet: Recovery Plans
          colpos: A,H
          skiprow: 1
          skipfooter: 0 
          colnames:
            - Recipient_ID
            - URL
    EC21:
      path: N:\Project\51448_ARPA\DC1\6. Data\ExpenditureFromTreasury
      fn: April-2022-Quarterly-and-Annual-Reporting-Data-through-March-31-2022.xlsx
      var:
        Recipients:
          sheet: Recipients
          colpos: A:E
          skiprow: 1
          skipfooter: 0 
          colnames:
            - Recipient_ID
            - RecipientName
            - State
            - ReportingTier
            - RecipientType
        Projects:
          sheet: Projects
          colpos: A:L
          skiprow: 1
          skipfooter: 0 
          colnames:
            - Recipient_ID
            - RecipientName
            - State
            - ReportingTier
            - RecipientType
            - ProjectName
            - ExpenditureCategoryGroup
            - ExpenditureCategory
            - ProjectDescription
            - AdoptedBudget
            - Cumulative_Obligations
            - Cumulative_Expenditures
        











