name: Update JSONC with Branch Name (Python)

on:
  push:
    branches:
      - '*'  # Trigger on push to any branch

permissions:
  contents: write

jobs:
  update-jsonc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Create and run Python script to update settings.jsonc
        run: |
          echo 'import os, re, json

          # Get branch name from GITHUB_REF
          ref = os.environ.get("GITHUB_REF", "")
          branch_name = ref.split("/")[-1]

          # Read .jsonc file (remove simple "//" style comments)
          filename = "settings.jsonc"
          with open(filename, "r", encoding="utf-8") as f:
              raw = f.read()
              cleaned = re.sub(r"//.*", "", raw)

          # Load as JSON and update the "branch" key
          data = json.loads(cleaned)
          data["branch"] = branch_name

          # Write back as pure JSON (comments will be removed)
          with open(filename, "w", encoding="utf-8") as f:
              json.dump(data, f, indent=2)
          ' > update_branch.py

          python3 update_branch.py

      - name: Commit and push changes
        run: |
          git add settings.jsonc
          git commit -m "Update branch in settings.jsonc to ${GITHUB_REF##*/}" || echo "No changes to commit"
          git push origin ${GITHUB_REF##*/}